"""
Pydantic schemas for the YAML study configuration.

"""
from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

TaskType = Literal[
    "info_screen",
    "single_choice",
    "multi_choice",
    "likert",
    "slider",
    "number_input",
    "free_text",
    "va_interaction",
]


# ── Shared building blocks ────────────────────────────────────────────────────

class _StrictModel(BaseModel):
    model_config = ConfigDict(extra="allow")  # tolerate unknown keys for forward-compat


class GroundTruth(_StrictModel):
    type: Literal["exact", "set_match", "ordered_match", "regex"] = "exact"
    value: Any = None
    partial_credit: bool = True


class VAVariant(_StrictModel):
    description: str = ""
    frontend_id: str | None = None
    backend_id: str | None = None
    spawn_extra_args: str = ""
    mivais_config: dict[str, Any] = Field(default_factory=dict)


class ComposeConfig(_StrictModel):
    """Docker-compose-driven VA. When set on a VAConfig, Studio orchestrates the
    container via ``docker compose`` instead of spawning a local subprocess.

    The compose file is *not* generated by Studio — researchers write their own
    ``docker-compose.yml`` (or hand-craft one per VA) and Studio just runs
    ``up -d <service>`` / ``stop <service>`` against it. This keeps deployment
    primitives explicit and recipes shareable.
    """
    file: str                                  # path to docker-compose.yml (absolute or relative to study dir)
    service: str                               # the service name inside compose
    project: str | None = None                 # optional compose -p override
    recording_dir_host: str | None = None      # host path bind-mounted as the recording dir


class VAConfig(_StrictModel):
    system: str
    # Required for the local-subprocess case; ignored when `compose` is set.
    spawn_cmd: str = ""
    cwd: str | None = None
    health_check_url: str = ""
    iframe_url: str
    spawn_timeout_seconds: int = 30
    shutdown_grace_seconds: int = 5
    env: dict[str, str] = Field(default_factory=dict)
    variants: dict[str, VAVariant] = Field(default_factory=dict)
    
    recording_dir_override: str | None = None
    compose: ComposeConfig | None = None
    external: bool = False
    token_env: str | None = None
    token_param: str = "token"
    room_per_session: bool = True
    room_param: str = "room"

    @model_validator(mode="after")
    def _ensure_default_variant(self) -> "VAConfig":
        if not self.variants:
            self.variants = {"default": VAVariant(description="default variant")}
        return self

    @model_validator(mode="after")
    def _require_spawn_cmd_or_compose(self) -> "VAConfig":
        if not self.external and not self.spawn_cmd and self.compose is None:
            raise ValueError(
                "VAConfig needs `spawn_cmd:`, `compose: { file, service }`, or `external: true`"
            )
        return self


class Recording(_StrictModel):
    audio: Literal["none", "per_participant", "single_mic"] = "none"
    
    video: Literal["none", "screen"] = "none"
    transcribe: bool = False
    whisper_model: str = "small"
    whisper_language: str = "auto"
    retention_days: int = 365
    
    biometric: bool = False
    
    external_sensor: bool = False


class Role(_StrictModel):
    """A participant role declared at the study level.

    Roles are first-class for both singleplayer (Wizard-of-Oz: one code
    pre-bound to "wizard", another to "subject") and multiplayer (each
    cohort fills one slot per role). The `agent_id` is the role's MIVAIS
    agent identifier, forwarded into the VA's WS URL as `?role=<agent_id>`
    so the Gateway can register the participant under the correct role.
    """
    id: str
    name: str = ""
    description: str = ""
    agent_id: str | None = None
    capacity: int | None = None        # max participants per session; None = unlimited
    selectable: bool = True            # set False to hide from the self-assign picker (admin-only role)
    color: str | None = None           # optional hex (e.g. "#2563eb"); used in admin + lobby UI
    
    wizard_panel: bool = False


class UIConfig(_StrictModel):
    show_progress_bar: bool = True
    show_timer: bool = True
    timer_position: Literal["top_right", "top_left", "sidebar", "hidden"] = "top_right"
    task_description_position: Literal["top", "left", "overlay"] = "top"
    task_steps_visible: bool = True
    task_steps_position: Literal["right", "left", "hidden"] = "right"
    show_presence: bool = True
    theme: Literal["light", "dark", "auto"] = "light"


# ── Task primitives ──────────────────────────────────────────────────────────

class AutoCheckTrigger(_StrictModel):
    """A task_step trigger: fire when a MIVAIS event matches event_type
    (and optionally each key/value pair in `meta`) `count` times."""
    event_type: str
    count: int = 1
    meta: dict[str, Any] = Field(default_factory=dict)


class TaskStep(_StrictModel):
    """One entry in a task's right-sidebar checklist.

    `mode` controls who can tick the step:
      - manual : participant ticks the box; `auto_check_on:` is ignored if set.
      - auto   : only Studio can tick it, from a matching MIVAIS event. The
                 checkbox is read-only in the UI and the server rejects manual
                 ticks. Requires `auto_check_on:`.
      - either : both paths tick it (participant click OR auto-detect).
                 Default when `auto_check_on:` is present.
    When `mode` is omitted, it defaults to ``either`` if `auto_check_on:` is
    set, otherwise ``manual``.

    `required: true` means the participant cannot submit until the step is
    checked (regardless of who checks it).
    """
    id: str
    label: str
    auto_check_on: AutoCheckTrigger | None = None
    mode: Literal["manual", "auto", "either"] | None = None
    required: bool = False

    @model_validator(mode="after")
    def _resolve_mode(self) -> "TaskStep":
        if self.mode is None:
            self.mode = "either" if self.auto_check_on else "manual"
        if self.mode == "auto" and self.auto_check_on is None:
            raise ValueError(
                f"task_step '{self.id}' has mode=auto but no auto_check_on — "
                f"the participant would never be able to tick it"
            )
        return self


class WorldStateConfig(_StrictModel):
    """How a task initialises the VA's WorldState at task-start.

    - mode=continue (default): keep the VA's WorldState as the previous task
      left it. If `set:` is given, apply only those keys as a delta on top.
    - mode=replace: write every key in `initial:` to the WorldState, replacing
      the participant-facing scenario. Existing keys not listed in `initial:`
      are left untouched (the VA's job is to render coherently from the new
      keys; Studio does not delete stale state).
    - by_role: per-role override map — when a participant's role appears here,
      Studio writes the role-specific block instead of (or in addition to) the
      base block. Used in Wizard-of-Oz to give the wizard a different scenario
      than the subject without spawning a second VA.
    """
    mode: Literal["continue", "replace"] = "continue"
    set: dict[str, Any] = Field(default_factory=dict)
    initial: dict[str, Any] = Field(default_factory=dict)
    by_role: dict[str, "WorldStateConfig"] = Field(default_factory=dict)


class AdvanceConfig(_StrictModel):
    """Per-task override of study.advance_policy.

    - all: every participant must submit before the cohort advances (default in multiplayer).
    - first: as soon as one participant submits, everyone advances.
    - admin: admin clicks "advance now" from the session dashboard.
    """
    policy: Literal["all", "first", "admin"] | None = None
    timeout_seconds: int | None = None


class GotoTarget(_StrictModel):
    """Where a `next:` rule sends the participant when its condition matches.

    Exactly one of {task, block, action, next_task} should be set:
      - task:       jump to this task id (the loader verifies it exists)
      - block:      jump to the first task of this block id
      - action:     drop | end | skip_block
      - next_task:  true means "continue linearly" (same as no rule matching)
    """
    task: str | None = None
    block: str | None = None
    action: Literal["drop", "end", "skip_block"] | None = None
    next_task: bool = False

    @model_validator(mode="after")
    def _exactly_one(self) -> "GotoTarget":
        set_fields = sum([
            self.task is not None,
            self.block is not None,
            self.action is not None,
            bool(self.next_task),
        ])
        if set_fields != 1:
            raise ValueError(
                "GotoTarget must set exactly one of {task, block, action, next_task}"
            )
        return self


class NextRule(_StrictModel):
    """One branch in a task's `next:` block.

    ``when`` is a safe expression evaluated against the just-submitted answer.
    Allowed names: ``answer``, ``score``, ``correct``, ``role``, ``params``.
    Allowed operators: comparison, in/not in, and/or/not. No function calls.

    Use ``when: default`` for the catch-all rule (must be last).
    """
    when: str
    goto: GotoTarget


class _TaskBase(_StrictModel):
    id: str
    type: TaskType
    prompt_md: str = ""
    prompt_md_by_role: dict[str, str] = Field(default_factory=dict)
    prompt_md_by_lang: dict[str, str] = Field(default_factory=dict)
    body_md_by_lang: dict[str, str] = Field(default_factory=dict)
    timer_seconds: int | None = None
    optional: bool = False
    tags: list[str] = Field(default_factory=list)
    task_steps: list[TaskStep] = Field(default_factory=list)
    ground_truth: GroundTruth | None = None
    advance: AdvanceConfig | None = None
    with_va: bool = False
    va_system: str | None = None
    world_state: WorldStateConfig | None = None
    next: list[NextRule] | None = None


class InfoScreenTask(_TaskBase):
    type: Literal["info_screen"]
    body_md: str = ""
    video_url: str | None = None
    continue_label: str = "Continue"
    min_view_seconds: int = 0


class SingleChoiceTask(_TaskBase):
    type: Literal["single_choice"]
    options: list[dict[str, str]] = Field(default_factory=list)


class MultiChoiceTask(_TaskBase):
    type: Literal["multi_choice"]
    options: list[dict[str, str]] = Field(default_factory=list)
    min_selected: int = 0
    max_selected: int | None = None


class LikertItem(_StrictModel):
    id: str
    label: str
    description: str = ""
    reverse: bool = False


class LikertScale(_StrictModel):
    min: int = 1
    max: int = 7
    min_label: str = "Low"
    max_label: str = "High"
    step: int = 1


class LikertTask(_TaskBase):
    type: Literal["likert"]
    scale: LikertScale = Field(default_factory=LikertScale)
    items: list[LikertItem] = Field(default_factory=list)
    randomize_items: bool = False


class SliderTask(_TaskBase):
    """A single continuous value on a labeled range — e.g. confidence 0–100,
    perceived difficulty, or a probability estimate. The participant drags a
    slider; the recorded answer is one number."""
    type: Literal["slider"]
    min: float = 0
    max: float = 100
    step: float = 1
    min_label: str = ""
    max_label: str = ""
    unit: str = ""             # rendered after the live value, e.g. "%"
    default_value: float | None = None  # None → slider starts at the midpoint
    show_value: bool = True    # display the numeric value while dragging


class NumberInputTask(_TaskBase):
    """A typed numeric answer — e.g. 'how many outliers did you find?'.
    Stricter than free_text (the browser enforces numeric + bounds) and
    cleaner to analyze (the recorded answer is a number, not a string)."""
    type: Literal["number_input"]
    min: float | None = None
    max: float | None = None
    step: float = 1
    unit: str = ""
    placeholder: str = ""


class FreeTextTask(_TaskBase):
    type: Literal["free_text"]
    min_chars: int = 0
    max_chars: int = 5000
    placeholder: str = ""
    rows: int = 4


class VAInteractionAnswer(_StrictModel):
    type: Literal["capture_state", "text", "choice", "none"] = "none"
    world_state_key: str | None = None
    required: bool = False


class VAInteractionTask(_TaskBase):
    type: Literal["va_interaction"]
    variant: str = "default"
    parameters: dict[str, Any] = Field(default_factory=dict)
    mivais_config: dict[str, Any] = Field(default_factory=dict)
    answer: VAInteractionAnswer = Field(default_factory=VAInteractionAnswer)


Task = Annotated[
    InfoScreenTask
    | SingleChoiceTask
    | MultiChoiceTask
    | LikertTask
    | SliderTask
    | NumberInputTask
    | FreeTextTask
    | VAInteractionTask,
    Field(discriminator="type"),
]


class Block(_StrictModel):
    id: str
    name: str = ""
    description_md: str = ""
    randomize_within: bool = False
    tasks: list[Task] = Field(default_factory=list)


# ── Top-level study ──────────────────────────────────────────────────────────

class MetricEventMatch(_StrictModel):
    """Event matcher for metrics — same vocabulary as auto_check_on."""
    event_type: str = ""
    source: str | None = None          # "mivais" | "studio" | None = any
    meta: dict[str, Any] = Field(default_factory=dict)


class MetricConfig(_StrictModel):
    """One declarative behavioral metric, computed per participant from the
    event stream (see studio.metrics). Which fields apply depends on `kind`:

      count/rate : match (+ rate divides by scope duration, events/min)
      latency    : from → to (+ aggregate: mean|median|min|max, first_only)
      ratio      : numerator / (numerator + denominator)
      python     : module "studio.metrics.custom.<name>:callable" (+ params)

    `task:` scopes any kind to that task's time window(s).
    """
    model_config = ConfigDict(extra="allow", populate_by_name=True)

    id: str
    label: str = ""
    kind: Literal["count", "rate", "latency", "ratio", "python"]
    task: str | None = None
    # count / rate
    match: MetricEventMatch | None = None
    # latency ("from" is a Python keyword — YAML uses `from:`)
    from_: MetricEventMatch | None = Field(default=None, alias="from")
    to: MetricEventMatch | None = None
    aggregate: Literal["mean", "median", "min", "max"] = "median"
    first_only: bool = False
    # ratio
    numerator: MetricEventMatch | None = None
    denominator: MetricEventMatch | None = None
    # python
    module: str = ""
    params: dict[str, Any] = Field(default_factory=dict)

    @model_validator(mode="after")
    def _require_kind_fields(self) -> "MetricConfig":
        need = {
            "count": ["match"], "rate": ["match"],
            "latency": ["from_", "to"],
            "ratio": ["numerator", "denominator"],
            "python": ["module"],
        }[self.kind]
        missing = [("from" if f == "from_" else f) for f in need if not getattr(self, f)]
        if missing:
            raise ValueError(f"metric '{self.id}' (kind={self.kind}) is missing: {', '.join(missing)}")
        return self

    def engine_dict(self) -> dict[str, Any]:
        """Shape consumed by studio.metrics.compute_metrics (alias keys)."""
        d = self.model_dump(by_alias=True, exclude_none=True)
        return d


class ReplayEventType(_StrictModel):
    """One rule mapping matched events to a replay-timeline interaction
    category. Uses the same match vocabulary as MetricEventMatch /
    auto_check_on, so a researcher reuses the exact `event_type`/`meta`
    predicates they already wrote there instead of learning a second
    syntax. Rules are evaluated in declared order; first match wins."""
    match: MetricEventMatch
    category: str
    label: str | None = None


class ReplayCategory(_StrictModel):
    """Optional display override for a category referenced by `event_types`
    (built-in or researcher-defined). A category with no entry here still
    renders — it gets a stable, automatically hashed color, the same scheme
    already used for per-agent/per-participant lane colors — so declaring
    this is purely cosmetic, never required for a category to work."""
    key: str
    label: str | None = None
    color: str | None = None


class ReplayConfig(_StrictModel):
    """Researcher-defined event taxonomy for Studio's admin session replay
    timeline (which interactions get their own color/label/filter chip).
    Entirely optional — a study that declares none of this keeps Studio's
    built-in defaults for the VA systems it recognizes."""
    event_types: list[ReplayEventType] = Field(default_factory=list)
    categories: list[ReplayCategory] = Field(default_factory=list)


class StudyConfig(_StrictModel):
    id: str
    name: str
    version: int = 1
    mode: Literal["singleplayer", "multiplayer"] = "singleplayer"
    participants_required: int | None = None
    consent_text_md: str = ""
    consent_text_md_by_lang: dict[str, str] = Field(default_factory=dict)
    va: VAConfig | None = None
    va_systems: dict[str, VAConfig] = Field(default_factory=dict)
    primary_va_system: str | None = None
    roles: list[Role] = Field(default_factory=list)

    recording: Recording = Field(default_factory=Recording)
    ui: UIConfig = Field(default_factory=UIConfig)
    advance_policy: Literal["all", "first", "admin"] = "all"

    block_order: Literal["declared", "random", "round_robin", "latin_square"] = "declared"
    block_orders: list[list[str]] = Field(default_factory=list)

    parameters: dict[str, Any] = Field(default_factory=dict)

    completion_redirect_url: str | None = None
    completion_code: str | None = None

    metrics: list[MetricConfig] = Field(default_factory=list)

    replay: ReplayConfig = Field(default_factory=ReplayConfig)

    blocks: list[Block] = Field(default_factory=list)
    tasks: list[Task] | None = None       # flat-list shortcut; folded into blocks on load

    @model_validator(mode="after")
    def _fold_flat_tasks_into_block(self) -> "StudyConfig":
        if self.tasks and not self.blocks:
            self.blocks = [
                Block(id="main", name="Main", tasks=list(self.tasks))
            ]
            self.tasks = None
        if self.mode == "multiplayer" and not self.participants_required:
            raise ValueError("multiplayer studies must declare participants_required")
        return self

    @model_validator(mode="after")
    def _expand_prolific_shorthand(self) -> "StudyConfig":
        if (self.completion_redirect_url or "").strip().lower() == "prolific":
            self.completion_redirect_url = (
                "https://app.prolific.com/submissions/complete?cc={completion_code}"
            )
        return self

    @model_validator(mode="after")
    def _resolve_va_systems(self) -> "StudyConfig":
        # Promote `va:` shorthand → `va_systems: {"default": va}`.
        if self.va is not None and not self.va_systems:
            self.va_systems = {"default": self.va}
            if not self.primary_va_system:
                self.primary_va_system = "default"

        # Auto-pick the only declared system as primary.
        if not self.primary_va_system and len(self.va_systems) == 1:
            self.primary_va_system = next(iter(self.va_systems))

        # Multiple systems + no primary is ambiguous.
        if len(self.va_systems) > 1 and not self.primary_va_system:
            raise ValueError(
                "study declares multiple va_systems but no primary_va_system; "
                "set `primary_va_system: <id>` at the study level"
            )

        # If primary is set it must reference a real system.
        if self.primary_va_system and self.primary_va_system not in self.va_systems:
            raise ValueError(
                f"primary_va_system '{self.primary_va_system}' is not declared in va_systems "
                f"(known: {sorted(self.va_systems)})"
            )

        # Validate each task's va_system reference + ensure va_interaction has a VA available.
        for blk in self.blocks:
            for t in blk.tasks:
                ref = t.va_system
                if ref is not None and ref not in self.va_systems:
                    raise ValueError(
                        f"task '{t.id}' references unknown va_system '{ref}' "
                        f"(known: {sorted(self.va_systems)})"
                    )
                if t.type == "va_interaction" and not self.va_systems:
                    raise ValueError(
                        f"task '{t.id}' is a va_interaction but the study declares no "
                        f"`va:` or `va_systems:` block"
                    )

        return self

    @model_validator(mode="after")
    def _validate_flow_and_counterbalance(self) -> "StudyConfig":
        if self.mode == "multiplayer":
            for blk in self.blocks:
                for t in blk.tasks:
                    if t.next:
                        raise ValueError(
                            f"task '{t.id}' has `next:` rules but the study is multiplayer. "
                            f"Conditional flow is singleplayer-only in this version."
                        )

        # Every goto target must reference a real task/block id.
        task_ids = {t.id for b in self.blocks for t in b.tasks}
        block_ids = {b.id for b in self.blocks}
        for blk in self.blocks:
            for t in blk.tasks:
                if not t.next:
                    continue
                for rule in t.next:
                    g = rule.goto
                    if g.task and g.task not in task_ids:
                        raise ValueError(
                            f"task '{t.id}' next.goto.task='{g.task}' is unknown "
                            f"(known: {sorted(task_ids)[:8]}...)"
                        )
                    if g.block and g.block not in block_ids:
                        raise ValueError(
                            f"task '{t.id}' next.goto.block='{g.block}' is unknown "
                            f"(known: {sorted(block_ids)})"
                        )

        # block_orders shape: every entry is a permutation of block ids.
        if self.block_orders:
            declared = [b.id for b in self.blocks]
            declared_set = set(declared)
            for i, order in enumerate(self.block_orders):
                if set(order) != declared_set:
                    raise ValueError(
                        f"block_orders[{i}] = {order} is not a permutation of "
                        f"the declared block ids {declared}"
                    )

        return self

    def resolve_task_va_system(self, task: Task) -> str | None:
        """Return the va_system_id this task should target, or None if no VA is needed."""
        return task.va_system or self.primary_va_system

    def effective_roles(self) -> list[Role]:
        """Return declared roles, or a single implicit default if none are declared."""
        if self.roles:
            return self.roles
        return [Role(id="participant", name="Participant", agent_id="analyst")]

    def get_role(self, role_id: str) -> Role | None:
        for r in self.effective_roles():
            if r.id == role_id:
                return r
        return None

    def all_tasks(self) -> list[Task]:
        return [t for b in self.blocks for t in b.tasks]
